### ISSUE TITLE
Cannot reach the FTP server

### ISSUE THREAD

**Issue by wangfuzhou110** [open2c/cooler#255]
Hi,
It seems as if the link to the ftp server is broken now?

**Comment by mdozmorov** [comment]
Experiencing the same issue. ftp://cooler.csail.mit.edu/coolers is not responding. It seems like a recurrent issue, like #97. Would it be possible to fix?
Thanks,
Mikhail

**Comment by zuoyi93** [comment]
Hi,

I tried to access a file on the FTP server with the following code,
 
```
wget ftp://cooler.csail.mit.edu/coolers/hg19/Rao2014-GM12878-MboI-allreps-filtered.10kb.cool
```

but it gave me the following error

```
--2021-07-18 14:35:51--  ftp://cooler.csail.mit.edu/coolers/hg19/Rao2014-GM12878-MboI-allreps-filtered.10kb.cool
           => ‘Rao2014-GM12878-MboI-allreps-filtered.10kb.cool’
Resolving cooler.csail.mit.edu (cooler.csail.mit.edu)... 128.52.129.246
Connecting to cooler.csail.mit.edu (cooler.csail.mit.edu)|128.52.129.246|:21... failed: Connection refused.
```

Any thought? Thanks!

Yi

**Comment by thekswenson** [comment]
The ftp servers is up now, but the cooler directory is empty.   Any chance you could fix this please?

**Comment by nvictus** [comment]
Apologies for the inconvenience. The ftp server was constantly going down for different reasons and has been too cumbersome to maintain since changing institutions. 

Luckily, NSF has generously provided us with an **s3-compatible** bucket allocation on the [Open Storage Network](https://www.openstoragenetwork.org/): you can now find the example data at https://usgs2.osn.mghpcc.org/cooler01

The files are accessible over http as well. You can find a listing at https://usgs2.osn.mghpcc.org/cooler01/index.html

We will update the README shortly.
