### ISSUE TITLE
[Bug] `as_pixel` parameter when fetching matrix results in counts in some bins to be splited into two row

### ISSUE THREAD

**Issue by TTTPOB** [open2c/cooler#270]
```python
mcool.matrix(balance=False, join=True, as_pixels=True).fetch("chr1:134041600-134092800")
```
![image](https://user-images.githubusercontent.com/19909103/157868140-297958b4-2925-44e3-a2d0-50f5ead78e2d.png)

```python
mcool.matrix(balance=False).fetch("chr1:134041600-134092800")
```
![image](https://user-images.githubusercontent.com/19909103/157868188-daf63d2d-e74a-41c4-a833-bc01371cb841.png)

as you can see, the sum of contact number of the two rows equals to the total number
but in most bins, this will just not happen

```python
mcool.matrix(balance=False, join=True, as_pixels=True).fetch("chr7:79513600-79564800")
```
![image](https://user-images.githubusercontent.com/19909103/157868475-4042ef49-f504-462a-af92-b4e8e3fb60ec.png)

```python
mcool.matrix(balance=False, join=True).fetch("chr7:79513600-79564800")
```
![image](https://user-images.githubusercontent.com/19909103/157868516-c3af493f-6498-4ff6-97cb-6f4bb3988841.png)

data used in this issue is
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE130275
filename `GSE130275_mESC_WT_combined_2.6B.mcool`
resolution 51.2k, mcool path `::/8`
cooler version `0.8.10`

**Comment by nvictus** [comment]
Thank you for reporting this.

This is due to an old issue with zoomify/coarsen that existed when the file was created. It does cause occasional bins to get split, as you noticed. The issue was fixed in version `0.8.5`. 

Summing the split pixel counts will give the correct total count. Due to the way scipy sparse matrices work, operations such as `clr.matrix(sparse=True)` internally sum repeated pixels, as you showed, even before applying balancing weights, so the problem fixes itself in that case. The calculation of balancing weights are similarly not affected by this issue. The result is unexpected when one is working with pixels, though, so it should be advertised in the documentation, which isn't the case right now. I'll add an issue for that.

Fortunately, the base resolution will not have split pixels, so an easy fix is to re-zoomify using a recent cooler package version. In your case, the file is in the old V1 multi-resolution [layout](https://cooler.readthedocs.io/en/latest/schema.html#multi-resolution), so your highest (i.e. base) resolution is found in group `17` with a resolution of 100bp (which you can see if you inspect with `cooler attrs -L 0`).

```sh
$ cooler zoomify --balance -o mESC_WT_combined_2.6B.100.mcool GSE130275_mESC_WT_combined_2.6B.mcool::17
```

You also have the freedom to choose more natural resolutions than powers of 2 if you desire, e.g.:

```sh
$ cooler zoomify --balance --resolutions 100,200,500,1000,2000,5000N -o mESC_WT_combined_2.6B.100.mcool GSE130275_mESC_WT_combined_2.6B.mcool::17 
```

where the `5000N` is a shortcut that expands to `5000,10000,25000,50000,100000,250000...`.

Let me know if that resolves the issue.
