### ISSUE TITLE
'zoomify' creates .mcool with empty zoom levels

### ISSUE THREAD

**Issue by mgperry** [open2c/cooler#330]
I've created a multicool file from a 5kb resolution Hi-C dataset (around 7GB). The resulting 14GB .mcool file contains no information for zoom levels below 160kb, however the levels above this looks fine in HiGlass. I've confirmed the empty zoom levels using the python API - the bins are present but `matrix()` returns an empty sparse matrix.

zoomify also uses a very large amount of memory at peak (180GB according to LSF), which seems odd since it's an order of magnitude larger than the entire base dataset. It takes nearly an hour to run.

This is using version `3.9.1` on python `3.11.0`.

Has anyone encountered anything like this before?

**Comment by mgperry** [comment]
I've found the source of the problem, I was using hg38 coordinates rather than hg19, and by making that change the cooler is created as expected. If you guys think it's worth it, I'm happy to take a look at why file creation failed silently and how the empty file was created, otherwise we can mark this as closed.

**Comment by manzt** [comment]
Great to hear you've pinpointed the issue to coordinate system discrepancies (hg38 vs hg19). Resolving the silent file creation failure and empty file issue would be very helpful if you are interested in taking a look.

We'd need a reproducible example to have a look on our end. Otherwise, we can close this.
